/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/@shirt/book.glb --meta --types --output src/@gen/meshes/BookMesh.tsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    magazine_01_cover89: THREE.Mesh
  }
  materials: {
    magazine_01_cover89: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/book.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.magazine_01_cover89.geometry} material={materials.magazine_01_cover89} userData={{ name: 'magazine_01_cover89' }} />
    </group>
  )
}

useGLTF.preload('/book.glb')
