/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 public/@meshes/book.glb --types --shadows --transform --resolution 1024 --root public/@meshes --output src/@gen/meshes/BookMesh.tsx
*/

import React, { useRef } from "react"

import { useGLTF } from "@react-three/drei"
import type * as THREE from "three"
import { type GLTF } from "three-stdlib"

type GLTFResult = GLTF & {
  nodes: {
    magazine_01_cover89: THREE.Mesh
  }
  materials: {
    magazine_01_cover89: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/../../book-transformed.glb",
  ) as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.magazine_01_cover89.geometry}
        material={materials.magazine_01_cover89}
      />
    </group>
  )
}

useGLTF.preload("/../../book-transformed.glb")
